.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAFELY" "1" "February 2012" "" ""
.
.SH "NAME"
\fBsafely\fR \- secure and simple command\-line password store
.
.SH "SYNOPSIS"
\fBsafely [OPTIONS] COMMAND [ACCOUNT]\fR
.
.SH "DESCRIPTION"
\fBsafely\fR is a command\-line based, tool to manage password in an extremely easy to use and secure way\. The passwords database is a simple GnuPG encrypted JSON document; this makes manual access and manipulation of the database very simple\.
.
.SH "COMMANDS"
\fB\-c, \-\-create\fR
.
.P
\~\~\~\~\~\~ Create a new password db\.
.
.P
\fB\-a, \-\-add\fR
.
.P
\~\~\~\~\~\~ Add a new account\.
.
.P
\fB\-p, \-\-passwd\fR
.
.P
\~\~\~\~\~\~ Show given account\'s password\.
.
.P
\fB\-u, \-\-user\fR
.
.P
\~\~\~\~\~\~ Show given account\'s username\.
.
.P
\fB\-e, \-\-edit\fR
.
.P
\~\~\~\~\~\~ Edit the given account\.
.
.P
\fB\-r, \-\-remove\fR
.
.P
\~\~\~\~\~\~ Remove given account\.
.
.P
\fB\-s, \-\-search\fR
.
.P
\~\~\~\~\~\~ Remove the given account\.
.
.P
\fB\-d, \-\-dump\fR
.
.P
\~\~\~\~\~\~ Dump JSON database\.
.
.P
\fB\-t, \-\-tests\fR
.
.P
\~\~\~\~\~\~ Run the security tests only\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help\.
.
.SH "OPTIONS"
\fB\-D, \-\-db\fR
.
.P
\~\~\~\~\~\~ Specifies a custom path to the password database\.
.
.P
\fB\-Q, \-\-quiet\fR
.
.P
\~\~\~\~\~\~ Output errors only (i\.e\. no "[ok]" messages)\.
.
.P
\fB\-S, \-\-nosecure\fR
.
.P
\~\~\~\~\~\~ Ignore any security test failure\.
.
.P
\fB\-B, \-\-nobackup\fR
.
.P
\~\~\~\~\~\~ Do not create db file backups\.
.
.P
\fB\-A, \-\-noagent\fR
.
.P
\~\~\~\~\~\~ Use the internal dumb password agent, not the default gpg agent\.
.
.SH "ENVIRONMENT"
\fBGPG_AGENT_INFO\fR
.
.P
\~\~\~\~\~\~ Used to locate the gpg\-agent\. This is only used when \fB\-\-noagent\fR is not set\. The value consists of 3 colon delimited fields: the path to the Unix Domain Socket, the PID of the gpg\-agent and the protocol version which should be set to 1\.
.
.SH "FILES"
\fB~/\.safely\.db\fR
.
.P
\~\~\~\~\~\~ The default password database file\. The option \fB\-\-db\fR can be used to override it\.
.
.P
\fB~/\.safely\.db~\fR
.
.P
\~\~\~\~\~\~ The default password database file backup\. If the \fB\-\-db\fR option is set, this will change accordingly\. If the \fB\-\-nobackup\fR option is used, this file is not created/modified\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2011 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
