.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAFELY" "1" "October 2011" "" ""
.
.SH "NAME"
\fBsafely\fR \- secure and simple command\-line password store
.
.SH "SYNOPSIS"
\fBsafely COMMAND [ACCOUNT]\fR
.
.SH "DESCRIPTION"
\fBsafely\fR is a command\-line based, tool to manage password in an extremely easy to use and secure way\. The passwords database is a simple GnuPG encrypted JSON document; this makes manual access and manipulation of the database very simple\.
.
.SH "COMMANDS"
\fB\-c, \-\-create\fR
.
.P
\~\~\~\~\~\~ Create a new password db\.
.
.P
\fB\-a, \-\-add\fR
.
.P
\~\~\~\~\~\~ Add a new account\.
.
.P
\fB\-p, \-\-passwd\fR
.
.P
\~\~\~\~\~\~ Show given account\'s password\.
.
.P
\fB\-u, \-\-user\fR
.
.P
\~\~\~\~\~\~ Show given account\'s username\.
.
.P
\fB\-e, \-\-edit\fR
.
.P
\~\~\~\~\~\~ Edit the given account\.
.
.P
\fB\-\-remove, \-r\fR
.
.P
\~\~\~\~\~\~ Remove given account\.
.
.P
\fB\-s, \-\-search\fR
.
.P
\~\~\~\~\~\~ Remove the given account\.
.
.P
\fB\-d, \-\-dump\fR
.
.P
\~\~\~\~\~\~ Dump JSON database\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the help\.
.
.SH "ENVIRONMENT"
The following environment variables affect safely behaviour:
.
.P
\fBSAFELY_DB\fR
.
.P
\~\~\~\~\~\~ Specifies a custom path to the password database\.
.
.P
\fBSAFELY_NOBACKUP\fR
.
.P
\~\~\~\~\~\~ If set, a backup of the db is not created\.
.
.P
\fBSAFELY_NOSECURE\fR
.
.P
\~\~\~\~\~\~ If set, any security test failure is ignored\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2011 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
