language: c

install:
 - sudo apt-get install cmake libjansson-dev libgpgme11-dev liblockfile-dev

before_script:
 - cmake .

script:
 - make

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
