.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAFELY" "1" "August 2013" "" ""
.
.SH "NAME"
\fBsafely\fR \- pretty command\-line password manager
.
.SH "SYNOPSIS"
\fBsafely [OPTIONS] COMMAND [ACCOUNT]\fR
.
.SH "DESCRIPTION"
\fBsafely\fR is a command\-line tool to manage passwords\. It stores all your login information (usernames and passwords) in a simple, JSON\-formatted file, encrypted and signed using your OpenPGP key: this makes it pretty secure and allows manual decryption of the database when needed\.
.
.SH "COMMANDS"
\fB\-c, \-\-create\fR
.
.P
\~\~\~\~\~\~ Create a new password database\.
.
.P
\fB\-a, \-\-add\fR
.
.P
\~\~\~\~\~\~ Add the given account\.
.
.P
\fB\-p, \-\-passwd\fR
.
.P
\~\~\~\~\~\~ Show the given account\'s password\.
.
.P
\fB\-u, \-\-user\fR
.
.P
\~\~\~\~\~\~ Show the given account\'s username\.
.
.P
\fB\-e, \-\-edit\fR
.
.P
\~\~\~\~\~\~ Edit the given account\.
.
.P
\fB\-r, \-\-remove\fR
.
.P
\~\~\~\~\~\~ Remove the given account\.
.
.P
\fB\-s, \-\-search\fR
.
.P
\~\~\~\~\~\~ Search for the given pattern\.
.
.P
\fB\-d, \-\-dump\fR
.
.P
\~\~\~\~\~\~ Dump JSON database\.
.
.P
\fB\-t, \-\-tests\fR
.
.P
\~\~\~\~\~\~ Run the security tests only\.
.
.P
\fB\-v, \-\-version\fR
.
.P
\~\~\~\~\~\~ Show program\'s version and exit\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show program\'s help and exit\.
.
.SH "OPTIONS"
\fB\-D, \-\-db\fR
.
.P
\~\~\~\~\~\~ Specifies a custom path to the password database\.
.
.P
\fB\-K, \-\-keys\fR
.
.P
\~\~\~\~\~\~ Space\-separated list of keys to be used\.
.
.P
\fB\-H, \-\-hide\fR
.
.P
\~\~\~\~\~\~ Print the passwords in red on red to avoid shoulder surfing\.
.
.P
\fB\-Q, \-\-quiet\fR
.
.P
\~\~\~\~\~\~ Output errors only (i\.e\. no "[ok]" messages)\.
.
.P
\fB\-F, \-\-fuzzy\fR
.
.P
\~\~\~\~\~\~ Search for non\-exact (fuzzy) matches\.
.
.P
\fB\-S, \-\-nosecure\fR
.
.P
\~\~\~\~\~\~ Ignore any security test failure\.
.
.P
\fB\-B, \-\-nobackup\fR
.
.P
\~\~\~\~\~\~ Do not create database file backups\.
.
.P
\fB\-A, \-\-noagent\fR
.
.P
\~\~\~\~\~\~ Do not use the default gpg agent\.
.
.SH "ENVIRONMENT"
\fBGPG_AGENT_INFO\fR
.
.P
\~\~\~\~\~\~ Used to locate the gpg\-agent\. This is only used when \fB\-\-noagent\fR is not set\.
.
.SH "GPG CONFIGURATION"
Before starting, you may want to add the following config to your \fBgpg\.conf\fR:
.
.IP "" 4
.
.nf

default\-key <MYKEY>
default\-recipient\-self
.
.fi
.
.IP "" 0
.
.P
Where \fB<MYKEY>\fR is the ID of your key\. Otherwise the \fB\-\-keys\fR option must be provided\.
.
.SH "FILES"
\fB~/\.safely\.db\fR
.
.P
\~\~\~\~\~\~ The default password database file\. The option \fB\-\-db\fR can be used to override it\.
.
.P
\fB~/\.safely\.db~\fR
.
.P
\~\~\~\~\~\~ The default password database backup file\. If the \fB\-\-db\fR option is set, this will change accordingly\. If the \fB\-\-nobackup\fR option is used, this file is not created/modified\.
.
.P
\fB~/\.safely\.db\.lock\fR
.
.P
\~\~\~\~\~\~ The default password database lock file\. If the \fB\-\-db\fR option is set, this will change accordingly\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2011\-2012 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
