.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAFELY" "1" "September 2015" "" ""
.
.SH "NAME"
\fBsafely\fR \- pretty command\-line password manager
.
.SH "SYNOPSIS"
\fBsafely [OPTIONS] COMMAND [ACCOUNT]\fR
.
.SH "DESCRIPTION"
\fBsafely\fR is a command\-line tool to manage passwords\. It stores all your login information (usernames and passwords) in a simple JSON\-formatted file, encrypted and signed using your OpenPGP key: this makes it pretty secure and allows manual decryption of the database when needed\.
.
.SH "COMMANDS"
\fB\-c, \-\-create\fR
.
.P
\~\~\~\~\~\~ Create a new password database\.
.
.P
\fB\-a, \-\-add\fR
.
.P
\~\~\~\~\~\~ Add a new account to the database\.
.
.P
\fB\-p, \-\-pass\fR
.
.P
\~\~\~\~\~\~ Print the password of the given account\.
.
.P
\fB\-u, \-\-user\fR
.
.P
\~\~\~\~\~\~ Print the user name of the given account\.
.
.P
\fB\-2, \-\-2fa\fR
.
.P
\~\~\~\~\~\~ Print 2\-factor auth token for the given account\.
.
.P
\fB\-e, \-\-edit\fR
.
.P
\~\~\~\~\~\~ Modify the given account\.
.
.P
\fB\-r, \-\-remove\fR
.
.P
\~\~\~\~\~\~ Remove the given account\.
.
.P
\fB\-s, \-\-search\fR
.
.P
\~\~\~\~\~\~ Search the database for the given query\.
.
.P
\fB\-d, \-\-dump\fR
.
.P
\~\~\~\~\~\~ Dump the database in JSON format\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the program\'s help message and exit\.
.
.SH "OPTIONS"
\fB\-D, \-\-db\fR
.
.P
\~\~\~\~\~\~ Use this database file [default: ~/\.config/safely/passwords\.db]\.
.
.P
\fB\-K, \-\-keys\fR
.
.P
\~\~\~\~\~\~ Use these space\-separated GPG keys [default: ]\.
.
.P
\fB\-F, \-\-fuzzy\fR
.
.P
\~\~\~\~\~\~ Enable non\-exact (fuzzy) matches\.
.
.P
\fB\-N, \-\-print\-newline\fR
.
.P
\~\~\~\~\~\~ Force printing a trailing newline even if the output doesn\'t go to a terminal\.
.
.P
This is useful for piping safely output to programs that expect a trailing newline\.
.
.P
\fB\-Q, \-\-quiet\fR
.
.P
\~\~\~\~\~\~ Quiet output\.
.
.P
\fB\-B, \-\-no\-backup\fR
.
.P
\~\~\~\~\~\~ Do not create a backup of the database\.
.
.SH "ENVIRONMENT"
\fBGPG_AGENT_INFO\fR
.
.P
\~\~\~\~\~\~ Used to locate the gpg\-agent\.
.
.SH "FILES"
\fB~/\.config/safely/passwords\.db\fR
.
.P
\~\~\~\~\~\~ The default password database file\. The option \fB\-\-db\fR can be used to override it\.
.
.P
\fB~/\.config/safely/passwords\.db~\fR
.
.P
\~\~\~\~\~\~ The default password database backup file\. If the \fB\-\-db\fR option is set, this will change accordingly\. If the \fB\-\-no\-backup\fR option is used, this file is not created/modified\.
.
.P
\fB~/\.config/safely/passwords\.db\.lock\fR
.
.P
\~\~\~\~\~\~ The default password database lock file\. If the \fB\-\-db\fR option is set, this will change accordingly\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
